In [6]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Krishan\Paper_Leaks_India.csv")

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x91 in position 1017: invalid start byte

In [2]:
df

NameError: name 'df' is not defined

In [7]:
import os

print(os.path.exists(r"C:\Users\Krishan\Paper_Leaks_India.csv"))

True

In [8]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Krishan\Paper_Leaks_India.csv", encoding="cp1252")

In [9]:
df

,Date of Exam/Incident,Exam Name,Conducting Body,Conducting Body Type,Area(s) of Incident,Leak Confirmation Status,Action taken,Note about action Taken,Note about incident,References,Appeared Students
0,26-08-2024,B.Ed. 4th Sem Exam : Creating an Inclusive School,Tamil Nadu Teachers Education University,State,Tamilnadu,accused,Alternative Question Paper Used,Alternative Question Paper Used,Paper leaked on social media before exam,TNTEU registrar relieved after reports of B.Ed...,NaN
1,04-08-2024,MBA 1st year Exam,Pondicherry University,Central,Pondicherry,confirmed,Exam Cancelled,Legal action against exam mafia,Paper leaked on social media before exam,Pondicherry University First-year MBBS Exam Pa...,NaN
2,06-07-2024,Foreign Medical Graduate Examination,National Board of Examinations in Medical Scie...,Central,Kerala,accused,Legal action taken and claim dismissed,"No Rexam and checking of evidence, claim dismi...",Paper leaked on social media,‘So far no evidence’: Kerala Police on FMGE ‘p...,NaN
3,30-06-2024,Agriculture Development Officers,Punjab Public Service Comission,State,Punjab,accused,NaN,No Rexam,Claim: Offical demanded bribe for leaking paper,"Now, ADO recruitment exam in Punjab under pape...",NaN
4,18-06-2024,UGC NET 2024,National Testing Agency,Central,All India,accused,No Rexam,Exam cancellation decision overruled by Suprem...,accusation of paper leak,Supreme Court upholds decision to cancel UGC N...,NaN
...,...,...,...,...,...,...,...,...,...,...,...
61,01-05-2016,NEET Phase 1 2016,CBSE,Central,Uttar Pradesh,confirmed,Legal action taken,No Rexam,Cheating reported,NEET Phase 1 2016: Paper leaked in Varanasi - ...,NaN
62,25-05-2015,UP CPMT 2015,"King George's Medical University , Lucknow",State,Uttar Pradesh,confirmed,Legal action taken,No Rexam,Paper leaked on social media,Bid to leak UP CPMT answers: 3 MBBS students a...,NaN
63,03-05-2015,AIPMT 2015,CBSE,Central,All India,confirmed,Exam Cancelled,Legal action against exam mafia,Paper leaked on social media,"AIPMT cancelled, CBSE told to reconduct exam -...",NaN
64,30-03-2015,Provincial civil services preliminary examination,Uttar Pradesh Public Service Comission,State,Uttar Pradesh,confirmed,Exam Cancelled,Legal action against exam mafia,Paper leaked on social media before exam,Uttar Pradesh civil services exam cancelled af...,NaN
65,23-06-2014,UP CPMT 2014,"King George's Medical University , Ghaziabadd",State,Uttar Pradesh,confirmed,Exam Cancelled,Legal action against exam mafia,Paper leaked on social media,"CPMT 2014 paper leak: Aspirants dejected, dema...",NaN

In [ ]:
df.head()

In [ ]:
df.tail()

In [ ]:
df.info()

In [ ]:
df.shape

In [ ]:
df.columns

In [ ]:
df.isnull().sum()

In [ ]:
df.duplicated().sum()

In [ ]:
df.describe()

In [ ]:
df.describe(include='all')

In [ ]:
clean_df.info()

In [ ]:
clean_df = clean_df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

In [ ]:
clean_df.head()

In [ ]:
clean_df["Action taken"] = clean_df["Action taken"].fillna("Unknown")

In [ ]:
clean_df.isnull().sum()

In [ ]:
clean_df.duplicated().sum()

In [ ]:
clean_df.drop(columns=["Appeared Students"], inplace=True)

In [ ]:
clean_df["Action taken"] = clean_df["Action taken"].fillna("Unknown")

In [ ]:
clean_df.isnull().sum()

In [ ]:
clean_df["Date of Exam/Incident"].head(15)

In [ ]:
pd.to_datetime(clean_df["Date of Exam/Incident"])

In [ ]:
clean_df["Date of Exam/Incident"] = pd.to_datetime(
    clean_df["Date of Exam/Incident"],
    dayfirst=True
)

In [ ]:
clean_df.info()

In [ ]:
clean_df["Year"] = clean_df["Date of Exam/Incident"].dt.year

In [ ]:
clean_df["Month"] = clean_df["Date of Exam/Incident"].dt.month_name()

In [ ]:
clean_df["Month_No"] = clean_df["Date of Exam/Incident"].dt.month

In [ ]:
clean_df["Quarter"] = clean_df["Date of Exam/Incident"].dt.quarter

In [ ]:
clean_df.head()

In [ ]:
clean_df["Conducting Body"].unique()

In [ ]:
clean_df["Conducting Body Type"].unique()

In [ ]:
clean_df["Area(s) of Incident"].unique()

In [ ]:
clean_df["Leak Confirmation Status"].unique()

In [ ]:
clean_df["Action taken"].unique()

In [ ]:
clean_df["Conducting Body"].unique()

In [ ]:
clean_df.to_csv("Paper_Leaks_Clean.csv", index=False)

In [ ]:
# Total incidents by year
clean_df["Year"].value_counts().sort_index()

In [ ]:
# Top Exam Names
clean_df["Exam Name"].value_counts()

In [ ]:
# Top Conducting Bodies
clean_df["Conducting Body"].value_counts()

In [ ]:
# State-wise incidents
clean_df["Area(s) of Incident"].value_counts()

In [ ]:
# Leak confirmation status
clean_df["Leak Confirmation Status"].value_counts()

In [11]:
import pandas as pd

In [17]:
df = pd.read_csv(
    r"C:\Users\Krishan\Paper_Leaks_Clean.csv",
    encoding="cp1252"
)

In [18]:
df

,Date of Exam/Incident,Exam Name,Conducting Body,Conducting Body Type,Area(s) of Incident,Leak Confirmation Status,Action taken,Note about action Taken,Note about incident,References,Year,Month,Month_No,Quarter
0,2024-08-26,B.Ed. 4th Sem Exam : Creating an Inclusive School,Tamil Nadu Teachers Education University,State,Tamilnadu,accused,Alternative Question Paper Used,Alternative Question Paper Used,Paper leaked on social media before exam,TNTEU registrar relieved after reports of B.Ed...,2024,August,8,3
1,2024-08-04,MBA 1st year Exam,Pondicherry University,Central,Pondicherry,confirmed,Exam Cancelled,Legal action against exam mafia,Paper leaked on social media before exam,Pondicherry University First-year MBBS Exam Pa...,2024,August,8,3
2,2024-07-06,Foreign Medical Graduate Examination,National Board of Examinations in Medical Scie...,Central,Kerala,accused,Legal action taken and claim dismissed,"No Rexam and checking of evidence, claim dismi...",Paper leaked on social media,â€˜So far no evidenceâ€™: Kerala Police on FMG...,2024,July,7,3
3,2024-06-30,Agriculture Development OfficersÂ,Punjab Public Service Comission,State,Punjab,accused,Unknown,No Rexam,Claim: Offical demanded bribe for leaking paper,"Now, ADO recruitment exam in Punjab under pape...",2024,June,6,2
4,2024-06-18,UGC NET 2024,National Testing Agency,Central,All India,accused,No Rexam,Exam cancellation decision overruled by Suprem...,accusation of paper leak,Supreme Court upholds decision to cancel UGC N...,2024,June,6,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,2016-05-01,NEET Phase 1 2016,CBSE,Central,Uttar Pradesh,confirmed,Legal action taken,No Rexam,Cheating reported,NEET Phase 1 2016: Paper leaked in Varanasi - ...,2016,May,5,2
62,2015-05-25,UP CPMT 2015,"King George's Medical UniversityÂ , Lucknow",State,Uttar Pradesh,confirmed,Legal action taken,No Rexam,Paper leaked on social media,Bid to leak UP CPMT answers: 3 MBBS students a...,2015,May,5,2
63,2015-05-03,AIPMT 2015,CBSE,Central,All India,confirmed,Exam Cancelled,Legal action against exam mafia,Paper leaked on social media,"AIPMT cancelled, CBSE told to reconduct exam -...",2015,May,5,2
64,2015-03-30,Provincial civil services preliminary examination,Uttar Pradesh Public Service Comission,State,Uttar Pradesh,confirmed,Exam Cancelled,Legal action against exam mafia,Paper leaked on social media before exam,Uttar Pradesh civil services exam cancelled af...,2015,March,3,1
65,2014-06-23,UP CPMT 2014,"King George's Medical UniversityÂ , Ghaziabadd",State,Uttar Pradesh,confirmed,Exam Cancelled,Legal action against exam mafia,Paper leaked on social media,"CPMT 2014 paper leak: Aspirants dejected, dema...",2014,June,6,2

In [26]:
clean_df = df.copy()

## EDA (Exploratory Data Analysis)

In [21]:
# Total incidents by year
clean_df["Year"].value_counts().sort_index()

Year
2014     1
2015     3
2016     2
2017     3
2018     5
2019     3
2020     2
2021     8
2022    11
2023    15
2024    13
Name: count, dtype: int64

In [22]:
# Top Exam Names
clean_df["Exam Name"].value_counts()

Exam Name
High School Mathematics Exam                         3
Constable Exam                                       2
B.Ed. 4th Sem Exam : Creating an Inclusive School    1
MBA 1st year Exam                                    1
Foreign Medical Graduate Examination                 1
                                                    ..
NEET Phase 1 2016                                    1
UP CPMT 2015                                         1
AIPMT 2015                                           1
Provincial civil services preliminary examination    1
UP CPMT 2014                                         1
Name: count, Length: 63, dtype: int64

In [27]:
# Top Conducting Bodies
clean_df["Conducting Body"].value_counts()

Conducting Body
Uttar Pradesh Public Service Comission                                 3
Maharashtra State Board of Secondary and Higher Secondary Education    3
CBSE                                                                   3
National Testing Agency                                                2
Bihar Public service Comission                                         2
Assam Board of Secondary Education                                     2
West Bengal Board of Primary Education                                 2
Telangana State Public Service Commission                              2
Bihar School Examination Board                                         2
Railway Recruitment Board                                              2
Tamil Nadu Teachers Education University                               1
Pondicherry University                                                 1
National Board of Examinations in Medical Sciences (NBEMS)             1
Punjab Public Service Comission                                        1
Tripura Tribal Areas Autonomous District Council                       1
Devi Ahilya Vishwavidyalaya's (DAVV)                                   1
VIT                                                                    1
Jharkhand Public Service Commission                                    1
Uttar Pradesh Police Recruitment and Promotion Board                   1
Parul University                                                       1
Tripura Board of Secondary Education (TBSE)                            1
Savitribai PhuleÂ PuneÂ University                                     1
Central Selection Board of Constables, Bihar                           1
Private Center                                                         1
Barkatullah University                                                 1
Odisha Staff Selection Commission                                      1
AIIMS                                                                  1
Punjab School Education Board                                          1
Telangana Board of intermediate Education                              1
Madhya Pradesh Board of Secondary Education                            1
Rajasthan Public Service CommissionÂ                                   1
Rajasthan Staff Selection Board                                        1
Himachal Pradesh Staff Selection Commission                            1
Arunachal Pradesh Public Service Commission                            1
The Uttar Pradesh Subordinate Services Selection CommissionÂ           1
Uttar Pradesh State Board of High School and Intermediate Education    1
Jammu and Kashmir Services Selection Board                             1
Maharashtra Housing and Area Development Authority                     1
Gujarat Subordinate Service Selection Board                            1
Uttarakhand Subordinate Staff Selection Commission                     1
Department of Basic Education, Uttar Pradesh                           1
BOARD OF SECONDARY EDUCATION, Rajasthan                                1
National Law School of India University                                1
Kerala Public Service Commission                                       1
Karnataka School Examination and Assessment Board                      1
Board of Secondary Education, Odisha                                   1
Gujarat Police Recruitment Board                                       1
Indria Gandhi National Open University                                 1
Staff Selection Comission                                              1
Himachal Pradesh Board of School Education                             1
Haryana Public Service Commission                                      1
King George's Medical UniversityÂ , Lucknow                            1
King George's Medical UniversityÂ , Ghaziabadd                         1
Name: count, dtype: int64

In [24]:
# State-wise incidents
clean_df["Area(s) of Incident"].value_counts()

Area(s) of Incident
Uttar Pradesh        11
All India             7
Maharasthra           6
Bihar                 5
Kerala                3
Madhya Pradesh        3
Gujrat                3
Telangana             3
Rajasthan             3
Punjab                2
Tripura               2
Assam                 2
West Bengal           2
Odisha                2
Himachal Pradesh      2
Delhi                 2
Tamilnadu             1
Pondicherry           1
Jharkhand             1
Arunachal Pradesh     1
Jammu                 1
Uttarakhand           1
Karnataka             1
Haryana               1
Name: count, dtype: int64

In [25]:
# Leak confirmation status
clean_df["Leak Confirmation Status"].value_counts()

Leak Confirmation Status
confirmed    48
accused      18
Name: count, dtype: int64

In [28]:
clean_df["Exam Name"].value_counts().head(10)

Exam Name
High School Mathematics Exam                         3
Constable Exam                                       2
B.Ed. 4th Sem Exam : Creating an Inclusive School    1
MBA 1st year Exam                                    1
Foreign Medical Graduate Examination                 1
Agriculture Development OfficersÂ                    1
UGC NET 2024                                         1
ADC Recruitment Exam                                 1
MBA Semster Exam                                     1
VIT Engineering Exam                                 1
Name: count, dtype: int64